# coding: utf-8

"""
    Hydra API

    Specification of the Hydra REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import hydra_client
from hydra_client.models.project import Project  # noqa: E501
from hydra_client.rest import ApiException


class TestProject(unittest.TestCase):
    """Project unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProject(self):
        """Test Project"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hydra_client.models.project.Project()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
