# coding: utf-8

"""
    Hydra API

    Specification of the Hydra REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import hydra_client
from hydra_client.models.jobset_input import JobsetInput  # noqa: E501
from hydra_client.rest import ApiException


class TestJobsetInput(unittest.TestCase):
    """JobsetInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobsetInput(self):
        """Test JobsetInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hydra_client.models.jobset_input.JobsetInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
