# coding: utf-8

"""
    Hydra API

    Specification of the Hydra REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import hydra_client
from hydra_client.models.build_output import BuildOutput  # noqa: E501
from hydra_client.rest import ApiException


class TestBuildOutput(unittest.TestCase):
    """BuildOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBuildOutput(self):
        """Test BuildOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hydra_client.models.build_output.BuildOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
