# coding: utf-8

"""
    Hydra API

    Specification of the Hydra REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import hydra_client
from hydra_client.default_api import DefaultApi  # noqa: E501
from hydra_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = hydra_client.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_jobset(self):
        """Test case for create_jobset

        Creates a jobset in an existing project  # noqa: E501
        """
        pass

    def test_create_project(self):
        """Test case for create_project

        Create a project  # noqa: E501
        """
        pass

    def test_get_build(self):
        """Test case for get_build

        Retrieves a single build of a jobset by id  # noqa: E501
        """
        pass

    def test_get_evaluation(self):
        """Test case for get_evaluation

        Retrieves evaluations identified by build id  # noqa: E501
        """
        pass

    def test_get_job_sets(self):
        """Test case for get_job_sets

        retrieve a jobset overview for a project  # noqa: E501
        """
        pass

    def test_get_jobset(self):
        """Test case for get_jobset

        Retrieves a jobset designated by project and jobset id  # noqa: E501
        """
        pass

    def test_get_jobset_evals(self):
        """Test case for get_jobset_evals

        Retrieves all evaluations of a jobset  # noqa: E501
        """
        pass

    def test_get_project(self):
        """Test case for get_project

        Retrieves a project designated by name  # noqa: E501
        """
        pass

    def test_get_projects(self):
        """Test case for get_projects

        Retrieves all projects  # noqa: E501
        """
        pass

    def test_login(self):
        """Test case for login

        Log in using username/password credentials  # noqa: E501
        """
        pass

    def test_search(self):
        """Test case for search

        search for evaluations  # noqa: E501
        """
        pass

    def test_trigger_job_set(self):
        """Test case for trigger_job_set

        trigger jobsets  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
